<?php

namespace Database\Seeders;

use App\Models\NumberSeries;
use Illuminate\Database\Seeder;

/**
 * One counter per module that generates its own codes.
 *
 * firstOrCreate on (module, financial_year) — re-running must never reset
 * current_number, or the next save hands out a code that already exists.
 *
 * Only Category is here: it is the one master whose sheet says "autogenerated".
 * Product, Buyer, Supplier and Agent codes are typed by the user with a
 * duplicate check, per their sheets.
 */
class NumberSeriesSeeder extends Seeder
{
    public function run(): void
    {
        $series = [
            [
                'module'         => 'category',
                'prefix'         => 'CAT',
                'financial_year' => null,   // CAT001 does not restart each year
                'padding'        => 3,
                'reset_yearly'   => false,
            ],
        ];

        // inward-entry is financial-year-scoped (GT/INW/xxx/<FY>) and its rows
        // are created on demand by InwardEntryService::ensureNumberSeries() —
        // seeding a financial_year-less row here would just be a dead entry
        // the lookup (keyed on module + financial_year) never matches.

        foreach ($series as $row) {
            NumberSeries::firstOrCreate(
                ['module' => $row['module'], 'financial_year' => $row['financial_year']],
                $row
            );
        }

        $this->command?->info('Number series seeded.');
    }
}
