<?php

namespace Tests\Feature\Masters;

use App\Models\Category;
use App\Models\DocumentFormat;
use App\Models\NumberSeries;
use App\Models\Product;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CategoryTest extends TestCase
{
    use RefreshDatabase;

    /**
     * `code` is outside $fillable on purpose — it is assigned by
     * NumberSeriesService — so fixtures set it with forceCreate.
     */
    private function actingAsRole(string $role): User
    {
        $user = User::factory()->create(['status' => true]);
        $user->assignRole($role);

        return $user;
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this->seed();
    }

    /*
    |--------------------------------------------------------------------------
    | Code generation — sheet col A, "autogenerated"
    |--------------------------------------------------------------------------
    */

    public function test_codes_are_generated_sequentially(): void
    {
        $user = $this->actingAsRole('Super Admin');

        foreach (["Men's Shirts", "Men's T-Shirts", "Men's Bottoms"] as $name) {
            $this->actingAs($user)
                ->post(route('masters.categories.store'), ['name' => $name, 'status' => 'active'])
                ->assertRedirect(route('masters.categories.index'));
        }

        $this->assertSame(
            ['CAT001', 'CAT002', 'CAT003'],
            Category::orderBy('id')->pluck('code')->all()
        );
    }

    public function test_next_code_skips_a_code_already_in_use(): void
    {
        Category::forceCreate(['code' => 'CAT001', 'name' => 'Woven Garments', 'status' => 'active']);

        $user = $this->actingAsRole('Super Admin');

        $this->actingAs($user)
            ->get(route('masters.categories.create'))
            ->assertOk()
            ->assertSee('CAT002');

        $this->actingAs($user)
            ->post(route('masters.categories.store'), [
                'name'   => "Men's T-shirt",
                'status' => 'active',
            ])
            ->assertRedirect(route('masters.categories.index'));

        $this->assertSame("Men's T-shirt", Category::where('code', 'CAT002')->value('name'));
        $this->assertSame(2, Category::count());
    }

    public function test_a_deleted_category_does_not_release_its_code(): void
    {
        $user = $this->actingAsRole('Super Admin');

        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'First', 'status' => 'active']);
        Category::first()->delete();
        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'Second', 'status' => 'active']);

        // CAT001 stays retired — it is on documents that were already sent.
        $this->assertSame('CAT002', Category::withoutTrashed()->first()->code);
    }

    public function test_the_code_cannot_be_set_from_the_request(): void
    {
        $this->actingAs($this->actingAsRole('Super Admin'))
            ->post(route('masters.categories.store'), [
                'name'   => 'Injected',
                'status' => 'active',
                'code'   => 'HACKED',
            ]);

        $this->assertSame('CAT001', Category::first()->code);
    }

    public function test_concurrent_saves_cannot_share_a_code(): void
    {
        // The counter is the shared resource; assert it moves once per save
        // rather than being derived from a stale read.
        $user = $this->actingAsRole('Super Admin');

        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'A', 'status' => 'active']);
        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'B', 'status' => 'active']);

        $this->assertSame(2, NumberSeries::where('module', 'category')->value('current_number'));
        $this->assertSame(2, Category::distinct()->count('code'));
    }

    /*
    |--------------------------------------------------------------------------
    | CRUD
    |--------------------------------------------------------------------------
    */

    public function test_a_category_can_be_created_with_every_sheet_field(): void
    {
        $format = DocumentFormat::create(['name' => 'Standard PO', 'module' => 'po']);
        $user   = $this->actingAsRole('Super Admin');

        $this->actingAs($user)->post(route('masters.categories.store'), [
            'name'       => "Men's Shirts",
            'format_ids' => [$format->id],
            'status'     => 'active',
            'remarks'    => 'All shirt products',
        ])->assertRedirect();

        $category = Category::first();

        $this->assertSame("Men's Shirts", $category->name);
        $this->assertTrue($category->formats->contains('id', $format->id));
        $this->assertSame('active', $category->status);
        $this->assertSame('All shirt products', $category->remarks);

        // HasAuditColumns fills these without the service being asked to.
        $this->assertSame($user->id, $category->created_by);
        $this->assertSame($user->id, $category->updated_by);
    }

    public function test_duplicate_names_are_rejected(): void
    {
        $user = $this->actingAsRole('Super Admin');

        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'Dup', 'status' => 'active']);

        $this->actingAs($user)
            ->post(route('masters.categories.store'), ['name' => 'Dup', 'status' => 'active'])
            ->assertSessionHasErrors('name');

        $this->assertSame(1, Category::count());
    }

    public function test_a_category_can_be_updated_but_its_code_cannot(): void
    {
        $user = $this->actingAsRole('Super Admin');
        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'Before', 'status' => 'active']);

        $category = Category::first();

        $this->actingAs($user)->put(route('masters.categories.update', $category), [
            'name'   => 'After',
            'status' => 'inactive',
            'code'   => 'CHANGED',
        ])->assertRedirect();

        $category->refresh();
        $this->assertSame('After', $category->name);
        $this->assertSame('inactive', $category->status);
        $this->assertSame('CAT001', $category->code);
    }

    public function test_status_toggles(): void
    {
        $user     = $this->actingAsRole('Super Admin');
        $category = Category::forceCreate(['code' => 'CAT900', 'name' => 'Toggle me', 'status' => 'active']);

        $this->actingAs($user)->patch(route('masters.categories.toggle-status', $category));
        $this->assertSame('inactive', $category->refresh()->status);

        $this->actingAs($user)->patch(route('masters.categories.toggle-status', $category));
        $this->assertSame('active', $category->refresh()->status);
    }

    public function test_a_category_is_soft_deleted(): void
    {
        $category = Category::forceCreate(['code' => 'CAT900', 'name' => 'Bye', 'status' => 'active']);

        $this->actingAs($this->actingAsRole('Super Admin'))
            ->delete(route('masters.categories.destroy', $category))
            ->assertRedirect();

        $this->assertSoftDeleted($category);
    }

    public function test_a_category_in_use_by_products_cannot_be_deleted(): void
    {
        $category = Category::forceCreate(['code' => 'CAT900', 'name' => 'In use', 'status' => 'active']);
        Product::create([
            'category_id'     => $category->id,
            'item_group_code' => 'PRD001',
            'name'            => 'A product',
            'status'          => 'active',
        ]);

        $this->actingAs($this->actingAsRole('Super Admin'))
            ->delete(route('masters.categories.destroy', $category))
            ->assertSessionHas('error');

        $this->assertNotSoftDeleted($category);
    }

    /*
    |--------------------------------------------------------------------------
    | Filters
    |--------------------------------------------------------------------------
    */

    public function test_the_list_can_be_searched_and_filtered_by_status(): void
    {
        Category::forceCreate(['code' => 'CAT001', 'name' => 'Cotton Shirts', 'status' => 'active']);
        Category::forceCreate(['code' => 'CAT002', 'name' => 'Denim Jeans', 'status' => 'inactive']);

        $user = $this->actingAsRole('Super Admin');

        $this->actingAs($user)->get(route('masters.categories.index', ['search' => 'Cotton']))
            ->assertSee('Cotton Shirts')->assertDontSee('Denim Jeans');

        $this->actingAs($user)->get(route('masters.categories.index', ['status' => 'inactive']))
            ->assertSee('Denim Jeans')->assertDontSee('Cotton Shirts');
    }

    public function test_sorting_ignores_a_column_that_is_not_whitelisted(): void
    {
        Category::forceCreate(['code' => 'CAT001', 'name' => 'A', 'status' => 'active']);

        // An unwhitelisted column must not reach ORDER BY.
        $this->actingAs($this->actingAsRole('Super Admin'))
            ->get(route('masters.categories.index', ['sort' => 'created_by); drop table categories; --']))
            ->assertOk();

        $this->assertSame(1, Category::count());
    }

    /*
    |--------------------------------------------------------------------------
    | Permissions
    |--------------------------------------------------------------------------
    */

    public function test_a_role_without_category_view_is_denied(): void
    {
        // Packing has product.view but no category.* at all.
        $this->actingAs($this->actingAsRole('Packing'))
            ->get(route('masters.categories.index'))
            ->assertForbidden();
    }

    public function test_a_view_only_role_cannot_create_or_delete(): void
    {
        // Merchandising has category.view only.
        $user     = $this->actingAsRole('Merchandising & Manufacturing');
        $category = Category::forceCreate(['code' => 'CAT001', 'name' => 'Read only', 'status' => 'active']);

        $this->actingAs($user)->get(route('masters.categories.index'))->assertOk();
        $this->actingAs($user)->get(route('masters.categories.create'))->assertForbidden();
        $this->actingAs($user)->post(route('masters.categories.store'), ['name' => 'X', 'status' => 'active'])->assertForbidden();
        $this->actingAs($user)->get(route('masters.categories.edit', $category))->assertForbidden();
        $this->actingAs($user)->delete(route('masters.categories.destroy', $category))->assertForbidden();
    }

    public function test_guests_are_redirected_to_login(): void
    {
        $this->get(route('masters.categories.index'))->assertRedirect(route('login'));
    }
}
